services:
  - type: web
    name: text-scanner-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: chrome-extension://* 